# ~/.config/yazi/keymap.toml

# From: https://yazi-rs.github.io/docs/tips
# Close input dialog with ONE <ESC> keypress
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# ya pack -a yazi-rs/plugins:jump-to-char
[[manager.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to CHAR"
